apiVersion: v1
kind: Service
metadata:
  name: tienda-frontend
  namespace: tienda
spec:
  type: NodePort
  selector:
    app: tienda-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
